apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001 
spec:
  capacity:
    storage: 50Gi 
  accessModes:
  - ReadWriteMany
  nfs: 
    path: /nfs
    server: nfs.example.com
  persistentVolumeReclaimPolicy: Recycle
